### ISSUE TITLE
ダイス未指定のときに卓参加後1回目の発言が送信されない

### ISSUE THREAD

**Issue by blhsrwznrghfzpr** [ukatama/nekotaku#41]
# 現象
- 卓作成時に、「ダイスの種類」を未指定で作成したときに、チャットの発言が1回目だけ送信できない
- 2回目以降は問題なく送信される。
- 新しいウィンドウで開いたときや、一度卓から出て卓に参加したときにも、1回目のチャットが送信されない。
- ブラウザのコンソールに以下のように表示される。
![image](https://user-images.githubusercontent.com/7685946/51433741-8d210600-1c94-11e9-8563-310f2c75892a.png)
- ダイスの種類を指定すると正常に送信できる。

# 確認環境
確認日時: 2019年1月20日 9時ごろ
ねこ卓お試し鯖、どどんとふ公式鯖にて確認
クライアント: Windows10+Chrome、iOS12+Safariにて確認

**Comment by ukatama** [comment]
詳細なIssue、ありがとうございます。
未指定にできることがバグです。
