### ISSUE TITLE
マップ上でキャラクター情報が表示されない

### ISSUE THREAD

**Issue by blhsrwznrghfzpr** [ukatama/nekotaku#42]
v1.7.0で追加されたはずのマップ上でのキャラクター情報が表示されない

確認日時: 2019年1月20日9時45分ごろ
ねこ卓お試し鯖、どどんとふ公式鯖にて確認
（2019年1月19日23時ごろのどどんとふ公式鯖では表示されてたように思えるのですが、記憶違いかもしれません）
Windows10+Chromeを使用

**Comment by ukatama** [comment]
1.8.0のバグのようです。修正します。
