### ISSUE TITLE
1.9.1に更新後、nekotaku-toolsでupdatedAtが取得できなくなった

### ISSUE THREAD

**Issue by daicyan** [ukatama/nekotaku#46]
1.8.0まではnekotaklu-toolsからListRoomsで取得できていたjsonから、updateAtが消えています。部屋の定期削除で使用していましたが、設計上の制約や仕様変更であれば別の方法を検討します。

  {
    "_id": "5c5ecc2cf5370d2f54b4abfd",
    "title": "公式鯖管理人のテスト部屋",
    "dice": "StellarKnights",
    "characterAttributes": [
      "HP",
      "SP",
      "MP",
      "SAN"
    ],
    "password": null,
    "roomId": "5c5ecc2cf5370d2f54b4abfd",
    "channels": [
      "メイン",
      "サブ",
      "おまけ",
      "雑談",
      "見学用",
      "階層1",
      "階層2",
      "階層3",
      "階層4",
      "階層5",
      "階層6",
      "階層7",
      "階層8",
      "階層9",
      "階層10",
      "階層11"
    ],
    "createdAt": 1549716667019,
    "id": "5c5ecc2cf5370d2f54b4abfd"
  }

**Comment by ukatama** [comment]
修正します。命名規則的に`updatedAt`だったと思われます……
使用上、修正バージョンまでの間に作成された部屋には`updatedAt`が付きません。ご了承ください。

**Comment by daicyan** [comment]
確認したところ、2019/1/19まではあったので、おそらくそれ以降のバージョンで作成または更新された部屋からはなくなっているようです。
フィールドがない部屋については、別の方法でなんとかします。

  {
    "_id": "5c3092595d6930581ca16050",
    "title": "てすと",
    "dice": "Cthulhu",
    "password": "yuu",
    "characterAttributes": [],
    "players": 1,
    "uid": "273e1666-7296-4a84-ae98-fc3179c30e4a",
    "createdAt": 1546687065904,
    "updatedAt": 1546687065904
  },
