### ISSUE TITLE
パスワード付きの卓に参加できない

### ISSUE THREAD

**Issue by blhsrwznrghfzpr** [ukatama/nekotaku#49]
# 現象
- パスワード付きの卓を新規作成すると卓に遷移しない
- パスワード付きの卓に参加の際に、パスワードを入力してもパスワードを要求する画面に遷移して、卓に入れない
- パスワード無しの部屋を新規作成して、卓に参加した後にパスワードを設定し一度卓から出た場合も、パスワードを入力しても卓に入れない

# 確認環境
- 確認日時: 2019年2月10日 7時45分ごろ
- サーバ: ねこ卓お試し鯖(v1.9.2)、どどんとふ公式鯖(v1.9.2)
- クライアント: Windows10+Chrome、iOS12+Safari
- 検証時に作成した部屋
https://nekotaku.nekometer.info/-LYI48Fk9u81rdpc5txN
https://nekotaku.onlinesession.app/5c5f549362535025af86eae4
password: test

**Comment by ukatama** [comment]
((((；ﾟДﾟ))))
